PATHS:
    VAST_TOOLS_DIR: "~/repositories/vast-tools"
    VASTDB_DIR: "~/projects/publication_viper_splicing/data/raw/VastDB/assemblies"
    TCGA_TOKEN: "~/projects/publication_viper_splicing/support/.private/gdc-user-token.txt"