PATHS:
    VAST_TOOLS:
        BIN: "~/repositories/vast-tools"
        VASTDB: "~/projects/publication_viper_splicing/data/raw/VastDB/assemblies"
    TCGA_TOKEN: "~/projects/publication_viper_splicing/support/.private/gdc-user-token.txt"